### ISSUE TITLE
Topic Management from Configuration

### ISSUE THREAD

**Issue by cricket007** [dropwizard/dropwizard-kafka#17]
Now that AdminClient was added, I suggest adding a way that, during the lifecycle startup, then topics are created if they don't already exist. 

Relevant methods: 

- https://kafka.apache.org/11/javadoc/org/apache/kafka/clients/admin/AdminClient.html#createTopics-java.util.Collection-
- https://kafka.apache.org/11/javadoc/org/apache/kafka/clients/admin/NewTopic.html

Configuration suggestion

```yaml
topics:
  - name: foo
    partitions: 3
    replicationFactor: 3
  # topic with additional configuration
  - name: bar
    partitions: 1
    replicationFactor: 5
    config:
      cleanup.policy: compact
```

Additionally, would be nice to have a healthcheck that verifies topic existance + configuration details, but that can be future issue.
