### ISSUE TITLE
Kafka Streams?

### ISSUE THREAD

**Issue by cricket007** [dropwizard/dropwizard-kafka#65]
Maybe borrow some ideas from https://github.com/streamthoughts/azkarra-streams

**Comment by mzamani1** [comment]
I'd love to support Kafka Streams, it's just a matter of me setting aside the time to do it. I welcome any PRs for this before I can tackle it, though!

**Comment by cricket007** [comment]
I could probably get started on at least the config objects

**Comment by cricket007** [comment]
Putting my thoughts here

1. Keep TopicsConfig the way it is
2. define generic config map like 
```
streams:
    applicationId:
    ... # all other real kafka configs
    config:  # name TBD
      input-topic: foo
      output-topic: bar
```

That way, you could start 

```java
kstream.from(props.get("input-topic")).map(this::process).to(props.get("output-topic")
```

**Comment by cricket007** [comment]
More thoughts.

Provide ability to chain together processor api via config
```
stream:
    appid: foo
    source: topic 
    steps:
        - step:
           name: filter # human readable 
           type: my-filter # polymorphism type 
        - step: 
            name: convert
            type: my-mapper 
            config:  # optional map 
                prop: foobar 
```
