### ISSUE TITLE
How to configure Serializer or Deserializers? 

### ISSUE THREAD

**Issue by cricket007** [dropwizard/dropwizard-kafka#8]
`StringSerializer`, for example has `encoding` configuration. How do you configure it? 

https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/serialization/StringSerializer.java#L33

Rather than just one-line class configurations, I would recommend objects

```yaml
valueSerializer:
  class: org.apache.kafka...StringSerializer
  config:
     value.serializer.encoding: "UTF-16"
```
